export class Proveedor {
    idProveedor:Number;
    tipoProveedor:String;
    cadena:String;
    nombre:String;
    checkin:Date;
    checout:Date;
    estrellas:Number;
    pais:String;
    ciudad:String;
    direccion:String;
    telefono:String;
    descripcionHotel:String;
    nombreGerenteGeneral:String;
    emailGerenteGeneral:String;
    notificarGerenteGeneral:Boolean;
    telefonoGerenteGeneral:String;
    nombreGerenteComercial:String;
    emailGerenteComercial:String;
    notificarGerenteComerial:Boolean;
    telefonoGerenteComercial:String;
    nombreContactoReservas:String;
    emailContactoReservas:String;
    notificarContactoReservas:Boolean;
    telefonoContactoReservas:String;
    nombreContactoGrupos:String;
    emailContactoGrupos:String;
    notificarContactoGrupos:Boolean;
    telefonoContactoGrupos:String;

}
